version: 1.0.{build}

environment:
  nodejs_version: '10'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - node --version
  - npm --version

test_script:
  - npm test
